spring:
  application:
    name: LMS

  datasource:
    url: jdbc:postgresql://localhost:5432/LMS_System
    username: postgres
    password: 1234

  flyway:
    enabled: true
    locations: classpath:db/migration

  jpa:
    hibernate:
      ddl-auto: none
